from __future__ import annotations

from typing import Any


ArchetypeSlot = dict[str, Any]
Archetype = list[ArchetypeSlot]


ARCHETYPES: dict[str, Archetype] = {
    "landing": [
        {
            "slot": "hero",
            "tags": ["hero", "banner", "header", "cta"],
            "required": True,
            "fallback": "hero_default",
            "renderer": "hero_render",
            "acceptance": {"required_tags": ["h1"], "min_links": 1},
        },
        {
            "slot": "features",
            "tags": ["feature", "features", "grid", "cards"],
            "required": True,
            "fallback": "features_default",
            "renderer": "features_render",
            "acceptance": {"required_tags": ["section"], "min_cards": 1},
        },
        {
            "slot": "testimonials",
            "tags": ["testimonial", "review", "quote"],
            "required": False,
            "fallback": "testimonials_default",
            "renderer": "testimonials_render",
            "acceptance": {"required_tags": ["section"]},
        },
        {
            "slot": "pricing",
            "tags": ["pricing", "plans", "tiers", "cards"],
            "required": False,
            "fallback": "pricing_default",
            "renderer": "pricing_render",
            "acceptance": {"required_tags": ["section"], "min_cards": 1},
        },
        {
            "slot": "faq",
            "tags": ["faq", "questions", "answers", "accordion"],
            "required": False,
            "fallback": "faq_default",
            "renderer": "faq_render",
            "acceptance": {"required_tags": ["section"]},
        },
        {
            "slot": "cta",
            "tags": ["cta", "action", "button", "signup"],
            "required": True,
            "fallback": "cta_default",
            "renderer": "cta_render",
            "acceptance": {"required_tags": ["a"]},
        },
        {
            "slot": "footer",
            "tags": ["footer"],
            "required": True,
            "fallback": "footer_default",
            "renderer": "footer_render",
            "acceptance": {"root_tags": ["footer"]},
        },
    ],
    "dashboard": [
        {
            "slot": "sidebar",
            "tags": ["nav", "sidebar", "menu"],
            "required": True,
            "fallback": "sidebar_default",
            "renderer": "sidebar_render",
            "acceptance": {"required_tags": ["nav"], "min_links": 1},
        },
        {
            "slot": "header",
            "tags": ["header", "topbar", "toolbar"],
            "required": True,
            "fallback": "header_default",
            "renderer": "header_render",
            "acceptance": {"required_tags": ["h1"]},
        },
        {
            "slot": "stats",
            "tags": ["card", "metric", "stat", "kpi"],
            "required": True,
            "fallback": "stats_default",
            "renderer": "stats_render",
            "acceptance": {"required_tags": ["section"], "min_cards": 1},
        },
        {
            "slot": "filters",
            "tags": ["filter", "filters", "toolbar", "search"],
            "required": False,
            "fallback": "filters_default",
            "renderer": "filters_render",
            "acceptance": {"required_tags": ["section"]},
        },
        {
            "slot": "charts",
            "tags": ["chart", "graph", "analytics", "trend"],
            "required": False,
            "fallback": "charts_default",
            "renderer": "charts_render",
            "acceptance": {"required_tags": ["section"]},
        },
        {
            "slot": "table",
            "tags": ["table", "data", "list", "transactions"],
            "required": True,
            "fallback": "table_default",
            "renderer": "table_render",
            "acceptance": {"required_tags": ["table"]},
        },
        {
            "slot": "widgets",
            "tags": ["widget", "panel", "activity"],
            "required": False,
            "fallback": "widgets_default",
            "renderer": "widgets_render",
            "acceptance": {"required_tags": ["section"]},
        },
    ],
    "docs": [
        {
            "slot": "nav",
            "tags": ["nav", "toc", "menu", "sidebar"],
            "required": True,
            "fallback": "docs_nav_default",
            "renderer": "docs_nav_render",
            "acceptance": {"root_tags": ["nav"], "min_links": 1},
        },
        {
            "slot": "article_header",
            "tags": ["header", "title", "article"],
            "required": True,
            "fallback": "article_header_default",
            "renderer": "article_header_render",
            "acceptance": {"required_tags": ["h1"]},
        },
        {
            "slot": "content_body",
            "tags": ["content", "article", "text", "body"],
            "required": True,
            "fallback": "content_body_default",
            "renderer": "content_body_render",
            "acceptance": {"required_tags": ["article"]},
        },
        {
            "slot": "code",
            "tags": ["code", "example", "snippet"],
            "required": False,
            "fallback": "code_block_default",
            "renderer": "code_block_render",
            "acceptance": {"required_tags": ["pre", "code"]},
        },
        {
            "slot": "footer",
            "tags": ["footer"],
            "required": True,
            "fallback": "footer_default",
            "renderer": "footer_render",
            "acceptance": {"root_tags": ["footer"]},
        },
    ],
    "catalog": [
        {
            "slot": "catalog_header",
            "tags": ["catalog", "header", "library", "directory"],
            "required": True,
            "fallback": "catalog_header_default",
            "renderer": "catalog_header_render",
            "acceptance": {"required_tags": ["h1"]},
        },
        {
            "slot": "catalog_filters",
            "tags": ["filters", "search", "tag", "toolbar", "catalog"],
            "required": True,
            "fallback": "catalog_filters_default",
            "renderer": "catalog_filters_render",
            "acceptance": {"required_tags": ["section"]},
        },
        {
            "slot": "catalog_list",
            "tags": ["cards", "list", "catalog", "items", "grid"],
            "required": True,
            "fallback": "catalog_list_default",
            "renderer": "catalog_list_render",
            "acceptance": {"required_tags": ["section"], "min_cards": 1},
        },
        {
            "slot": "catalog_detail",
            "tags": ["detail", "panel", "preview", "catalog"],
            "required": True,
            "fallback": "catalog_detail_default",
            "renderer": "catalog_detail_render",
            "acceptance": {"required_tags": ["section"]},
        },
        {
            "slot": "footer",
            "tags": ["footer"],
            "required": True,
            "fallback": "footer_default",
            "renderer": "footer_render",
            "acceptance": {"root_tags": ["footer"]},
        },
    ],
}
